version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    container_name: jaeger
    restart: on-failure
    ports:
      - 5775:5775/udp # agent - accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
      - 6831:6831/udp # agent - accept jaeger.thrift over compact thrift protocol
      - 6832:6832/udp # agent - accept jaeger.thrift over binary thrift protocol
      - 5778:5778     # agent - serve configs
      - 16686:16686   # serve frontend
      - 14268:14268   # collector - accept jaeger.thrift directly from clients
      - 14250:14250   # collector - accept model.proto
      - 9411:9411     # collector - Zipkin compatible endpoint (optional)
  cassandra:
    image: 'docker.io/bitnami/cassandra:3-debian-10'
    container_name: cassandra
    restart: on-failure
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - './pkg/database/resource/script.cql:/docker-entrypoint-initdb.d/script.cql'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_USER=cassandra